# Generated by Django 4.2.2 on 2024-05-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
